# Generated by Django 5.2.11 on 2026-02-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.studymaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=300)),
                ('option_b', models.CharField(blank=True, max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('flashcard', 'Flashcard')], default='mcq', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.studymaterial')),
            ],
        ),
    ]
